---
root: true
extends:
  - 'plugin:@gitlab/default'
ignorePatterns:
 - vite.config.js
 - postcss.config.js
env:
  jest/globals: true
plugins:
  - jest
rules:
  # Disallow console.log while allowing other console methods.
  no-console:
    - error
    - allow:
        - info
        - warn
        - error
