---
include:
  - local: .gitlab/ci/*.gitlab-ci.yml

stages:
  - lint
  - security
  - test
  - prebuild
  - build
  - deploy

variables:
  # Versions specified here are production versions
  # See also .tool-versions file for development versions
  # See also GO_VERSION declared in test:go job
  COREPACK_VERSION: "0.28.1"
  GO_VERSION: "1.22"
  GO_VERSION_PREVIOUS: "1.21"
  GOLANGCI_LINT_VERSION: "1.58.1"
  HUGO_VERSION: "0.128.0"
  # Lychee Docker image tags use SHAs
  LYCHEE_VERSION: "0a54079"
  NODE_VERSION: "20"
  SHELLCHECK_VERSION: "0.10.0"
  YQ_VERSION: "4.44.1"

  # Linux distribution versions
  ALPINE_VERSION: "3.19"
  DEBIAN_VERSION: "bookworm"

  # Other versions
  ASDF_VERSION: "0.14.0"

workflow:
  name: '$DOCS_PROJECT_PIPELINE_TYPE'
  rules:
    # Prevent branch pipelines if an MR is open on the branch.
    - if: $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        DOCS_PROJECT_PIPELINE_TYPE: "MR pipeline: branch $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      variables:
        DOCS_PROJECT_PIPELINE_TYPE: "Default branch pipeline"
