stages:
  - test

variables:
  DOCKER_VERSION: "20.10.15"
  GO_VERSION: "1.21"
  DEBIAN_VERSION: "bullseye"
  POLICY: pull

workflow:
  rules: &workflow_rules
    # For merge requests, create a pipeline.
    - if: '$CI_MERGE_REQUEST_IID'
    # For `main` branch, create a pipeline (this includes on schedules, pushes, merges, etc.).
    - if: '$CI_COMMIT_BRANCH == "main"'
    # For tags, create a pipeline.
    - if: '$CI_COMMIT_TAG'

default:
  image: golang:${GO_VERSION}-${DEBIAN_VERSION}
  tags:
    - gitlab-org

.go-matrix-job:
  parallel:
    matrix:
      - GO_VERSION: ["1.19", "1.20", "1.21"]

################################################################################
# Test jobs
################################################################################

shellcheck-tests:
  image: koalaman/shellcheck-alpine:latest
  script:
    - shellcheck scripts/*.sh

go-tests:
  extends:
    - .go-matrix-job
  script:
    - make go-tests
