################################################################################
# prebuild and build stage jobs
################################################################################

# During the migration, we need to fetch YAML data files before building the frontend.
# See doc/post-processing.md for details.
prebuild:fetch_data:
  stage: prebuild
  extends:
    - .rules_dev_and_prod
  script:
    - go run cmd/gldocs/main.go fetch
  artifacts:
    paths:
      - data/navigation.yaml
    expire_in: 1d

prebuild:compile_frontend:
  stage: prebuild
  extends:
    - .frontend
    - .rules_dev_and_prod
  script:
    - yarn build
  needs:
    - job: prebuild:fetch_data
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn/cache
  artifacts:
    paths:
      - themes/gitlab-docs/static/vite/
      - themes/gitlab-docs/static/gitlab_ui/
      - themes/gitlab-docs/static/icons.svg
      - data/icons.json
    expire_in: 1d

build:compile_site:
  image: hugomods/hugo:exts-${HUGO_VERSION}
  stage: build
  extends:
    - .yarn_install
    - .rules_dev_and_prod
  script:
    # Install additional dependencies
    - apk update && apk upgrade
    - apk add --no-cache curl coreutils make bash gcc libc-dev
    - wget https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq
    - chmod +x /usr/local/bin/yq
    # Print Hugo environment info
    - hugo env
    # Fetch docs content
    - make clone-docs-projects
    # Compile the site
    - hugo --gc --minify
    # Compress files with gzip
    - find public -type f -regex '.*\.\(css\|html\|js\|txt\|xml\)$' -exec gzip -f -k {} \;
    # Print the final size of the public directory
    - SIZE_AFTER_COMPRESS=$(du -sh public/ | awk '{print $1}')
    - echo -e "Size after adding compressed versions ..... $SIZE_AFTER_COMPRESS"
  needs:
    - prebuild:compile_frontend
  artifacts:
    paths:
      - public
    expire_in: 1d
