################################################################################
# Globally shared configuration
################################################################################

default:
  image: golang:${GO_VERSION}-${DEBIAN_VERSION}
  tags:
    - gitlab-org

#
# Shared configurations
#

.yarn_install:
  before_script:
    - node --version
    # https://github.com/nodejs/corepack?tab=readme-ov-file#manual-installs
    - npm uninstall -g yarn pnpm
    - npm install -g corepack@${COREPACK_VERSION}
    - corepack enable
    - yarn --version
    - yarn install --immutable

.frontend:
  image: node:${NODE_VERSION}-alpine${ALPINE_VERSION}
  extends:
    - .yarn_install

#
# Shared rules
#

.rules_dev:
  rules:
    - if: '$DOCS_PROJECT_PIPELINE_TYPE =~ /^MR pipeline.*/'

.rules_dev_and_prod:
  rules:
    - if: '$DOCS_PROJECT_PIPELINE_TYPE =~ /^MR pipeline.*/'
    - if: '$DOCS_PROJECT_PIPELINE_TYPE == "Default branch pipeline"'

.rules_prod:
  rules:
    - if: '$DOCS_PROJECT_PIPELINE_TYPE == "Default branch pipeline"'

.rules_asdf:
  rules:
    - if: '$DOCS_PROJECT_PIPELINE_TYPE =~ /^MR pipeline.*/'
      changes:
        - ".tool-versions"

.rules_docs:
  rules:
    - if: '$DOCS_PROJECT_PIPELINE_TYPE =~ /^MR pipeline.*/'
      changes:
        - "doc/**/*"
