################################################################################
# Test stage jobs
################################################################################

test:go:
  stage: test
  needs: []
  extends:
    - .rules_dev_and_prod
  parallel:
    matrix:
      # Should match GO_VERSION_PREVIOUS and GO_VERSION variables declared in `.gitlab-ci.yml`
      - GO_VERSION: ["1.21", "1.22"]
  script:
    - make go-tests

test:jest:
  stage: test
  needs: []
  extends:
    - .frontend
    - .rules_dev_and_prod
  script:
    - apk add make
    - make jest-tests

test:markdown-links:
  stage: test
  extends:
    - .rules_docs
  image:
    name: lycheeverse/lychee:sha-${LYCHEE_VERSION}-alpine
    entrypoint: [""]
  needs: []
  script:
    # See also markdown-link-tests in makefiles/Makefile.tests.mk
    - lychee --version
    - lychee --offline --include-fragments README.md doc/

# Check that asdf/mise dependencies install correctly
test:asdf-installation:
  stage: test
  extends:
    - .rules_asdf
  image: debian:${DEBIAN_VERSION}-slim
  needs: []
  script:
    - apt-get update && apt-get install -y --no-install-recommends curl git jq make python3-pip xz-utils
    - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v${ASDF_VERSION}
    - source "$HOME/.asdf/asdf.sh"
    # Set PIP_BREAK_SYSTEM_PACKAGES=1 because we mix Debian-installed Python packages and other Python packages.
    - PIP_BREAK_SYSTEM_PACKAGES=1 make install-dependencies

# Check docs content for Kramdown syntax
# This can be removed after we've completed the migration to Hugo
test:kramdown-audit:
  stage: test
  extends:
    - .rules_dev
  image: hugomods/hugo:exts-${HUGO_VERSION}
  needs: []
  allow_failure: true
  script:
    - apk update && apk upgrade
    - apk add --no-cache curl coreutils make bash gcc libc-dev
    - wget https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq
    - chmod +x /usr/local/bin/yq
    - make kramdown-audit
